In [1]:
import pandas as pd
import numpy as np
import requests

In [18]:
np.nan

nan

In [59]:
url = 'https://dash.engageminds.ai/api/oka/analysis/v1/event/report'
headers = {
        'Content-Type': 'application/json;charset=UTF-8'
    }
body1={"appKey":"P3ewIzs9gigHVSRLXqvF4xjubPwDz5MZ","pubAppId":175680,"fomulars":"[]","groups":"[{\"id\":\"e4a009fc-801d-4897-9b8b-e970b1efa37c\",\"display\":\"用户唯一id\",\"displayEn\":\"SSID\",\"value\":\"$ssid\",\"propType\":1,\"type\":1,\"category\":0,\"dataType\":2},{\"id\":\"43f16302-fe0f-4632-9582-7e376774b397\",\"display\":\"事件发生时间\",\"displayEn\":\"事件发生时间\",\"value\":\"#vp@event_date\",\"propType\":0,\"type\":2,\"virtualSql\":\"event.$sts\",\"category\":0,\"dataType\":3,\"customBucket\":null}]","tz":0,"dateType":2,"lang":"cn","dateValue":"[\"2024-09-28\",\"Yesterday\"]","events":"[{\"id\":\"34ab5561-c77b-4ea7-b6be-278a1766b469\",\"f\":[{\"id\":\"8d2aad77-0b16-4570-be20-dfd312b42ac9\",\"f\":{},\"columnName\":\"is_first_pay\",\"display\":\"is_first_pay\",\"displayEn\":\"is_first_pay\",\"selectType\":\"Number\",\"symbolType\":1,\"propType\":0,\"type\":0,\"category\":0,\"calcuSymbol\":\"Equal\",\"symbolId\":\"A01\",\"ftv\":[\"1\"],\"showCondition\":false}],\"eid\":\"In_appPurchases_BuySuccess\",\"display\":\"内购成功\",\"displayEn\":\"内购成功\",\"type\":1,\"countType\":{\"value\":\"unique\",\"name\":\"总人数\",\"nameEn\":\"Unique\"}}]","filters":"[{\"id\":\"e9804fd8-e4ba-430d-ba39-afb04f9b75c0\",\"eid\":\"\",\"f\":[{\"id\":\"a77bbbd2-1893-41f3-8bda-550b0c1c199b\",\"f\":{},\"columnName\":\"$country\",\"display\":\"国家/地区\",\"displayEn\":\"Country/Region\",\"selectType\":\"String\",\"symbolType\":2,\"propType\":1,\"type\":1,\"category\":0,\"calcuSymbol\":\"Is\",\"symbolId\":\"B01\",\"ftv\":[\"JP\"],\"showCondition\":false,\"d\":1}]}]"}

In [3]:
body2 = {"appKey":"P3ewIzs9gigHVSRLXqvF4xjubPwDz5MZ","pubAppId":175680,"fomulars":"[]","groups":"[{\"id\":\"461e9a02-7175-421b-a17e-02fa86ab28cd\",\"display\":\"用户唯一id\",\"displayEn\":\"SSID\",\"value\":\"$ssid\",\"propType\":1,\"type\":1,\"category\":0,\"dataType\":2},{\"id\":\"ef0f72c8-5b49-42bf-93da-4331c93e90b1\",\"display\":\"事件发生时间\",\"displayEn\":\"事件发生时间\",\"value\":\"#vp@event_date\",\"propType\":0,\"type\":2,\"virtualSql\":\"event.$sts\",\"category\":0,\"dataType\":3}]","tz":0,"dateType":2,"lang":"cn","dateValue":"[\"2024-09-28\",\"Yesterday\"]","events":"[{\"id\":\"81f8d820-14f3-4392-99e4-da998d3c200b\",\"f\":[],\"eid\":\"login\",\"display\":\"登录\",\"displayEn\":\"登录\",\"type\":1,\"countType\":{\"value\":\"unique\",\"name\":\"总人数\",\"nameEn\":\"Unique\"}}]","filters":"[{\"id\":\"03887e0a-a948-4dba-a563-d037087d8da1\",\"eid\":\"\",\"f\":[{\"id\":\"dec0483a-179a-48bf-a7db-d00a4c2f6bdd\",\"f\":{},\"columnName\":\"$country\",\"display\":\"国家/地区\",\"displayEn\":\"Country/Region\",\"selectType\":\"String\",\"symbolType\":2,\"propType\":1,\"type\":1,\"category\":0,\"calcuSymbol\":\"Is\",\"symbolId\":\"B01\",\"ftv\":[\"JP\"],\"showCondition\":false,\"d\":1}]}]"}

In [61]:
ng = requests.post(url, headers=headers, json=body1)
login =requests.post(url, headers=headers, json=body2)

In [62]:
ng.json()

{'code': 0,
 'status': 'enable',
 'msg': 'OK',
 'msgCN': 'OK',
 'data': {'data': [{'date': '2024-10-23',
    'ssid': '3M2AFIiYD49e9hlXwuJiso',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729691482776},
   {'date': '2024-10-07',
    'ssid': '3kbNIGADBCxteZGwTujMkx',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728341201677},
   {'date': '2024-10-23',
    'ssid': '2Tfn0VL41zCaZwhOPPp6zU',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729654831149},
   {'date': '2024-10-07',
    'ssid': 'eyUAQNamglLqoKRAUvGKz',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728282988124},
   {'date': '2024-10-30',
    'ssid': '66az20ik9GNGX7LZkrynGQ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730264402697},
   {'date': '2024-10-26',
    'ssid': '7UwuzYrD25MsAIHJOAu4Sr',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729907424887},
   {'date': '2024-11-02',
    'ssid': '15XPrBTNKE3sUu7O2zGSoZ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730584919601},
   {'date': '2024-10-12',
    'ssid': '4teHeM15Gl813NVg7mkeCV',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728764380419},
   {'date': '2024-10-15',
    'ssid': '6dixy2BHXWaGArZPk5Wo2H',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729034761705},
   {'date': '2024-10-21',
    'ssid': '6x19016kCyglckLDB22okT',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729512501933},
   {'date': '2024-10-30',
    'ssid': 'ZUSuqw9DyT3QpSJwbagZv',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730282575482},
   {'date': '2024-10-21',
    'ssid': '7IePNW6VizjMUgxzYtia33',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729515893288},
   {'date': '2024-10-24',
    'ssid': '5PDySHyC3FrP13w5YK6mLq',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729770294392},
   {'date': '2024-11-03',
    'ssid': '5ea4IjETiS5rCdUEAGtet2',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730621879459},
   {'date': '2024-10-17',
    'ssid': '6DMrxZ0CZ9LmpOg6et87WD',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729167837710},
   {'date': '2024-10-09',
    'ssid': '5oa2UHSauccI29k7RSre1H',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728481247953},
   {'date': '2024-10-16',
    'ssid': '7GXZJD8eoepzEFiSHHWG8x',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729068489626},
   {'date': '2024-10-03',
    'ssid': 'FotJe5sNWwnJb5QFqDNav',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1727946625272},
   {'date': '2024-10-22',
    'ssid': 'ViYst8xgIJXyFJisMFyY9',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729605979516},
   {'date': '2024-11-03',
    'ssid': '4qPTDrNq6TDJOej9tG9QqI',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730655561894},
   {'date': '2024-10-31',
    'ssid': '8ThgsJOl4V97nIgpaAz8j',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730396798554},
   {'date': '2024-10-31',
    'ssid': '7Bea58suJhoGGDQCGTuTAD',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730409673932},
   {'date': '2024-10-31',
    'ssid': '3USlzzH0IvMKSNM6uptQNY',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730377404747},
   {'date': '2024-10-01',
    'ssid': '1ZxEiZIVe5ftymmBTfkALD',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727755103927},
   {'date': '2024-10-18',
    'ssid': '63CA7f97NUg3Sr9Lj8EOVG',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729219945578},
   {'date': '2024-10-16',
    'ssid': '3ondZ5ZOM99tO5ZF5b0H3W',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729068419254},
   {'date': '2024-10-14',
    'ssid': 'sSwaAtR47yVpGEjMG30R6',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728887846048},
   {'date': '2024-11-04',
    'ssid': '6247C769q8oKFCPd1os0Vt',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730703842951},
   {'date': '2024-10-26',
    'ssid': '1b2g7w0zZh7Rwh1mrnEG93',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729954486386},
   {'date': '2024-10-09',
    'ssid': 'V5kWdUkHd8UTi36Ysq6MX',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728517680103},
   {'date': '2024-10-11',
    'ssid': '2xM3P2U6042HMt418M361s',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728683506347},
   {'date': '2024-10-08',
    'ssid': 'CqpHSc6syDl9zhOgJmugZ',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728370206387},
   {'date': '2024-11-04',
    'ssid': '6LCrsNxoEip2YdIcJBkFvE',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730704190506},
   {'date': '2024-10-25',
    'ssid': '7N3eU6tOZ7O8modxJO8H2Z',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729881044103},
   {'date': '2024-10-14',
    'ssid': '1cOJfiBaMtESk25widNKDX',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728939815822},
   {'date': '2024-11-04',
    'ssid': '50HHm7jGuHWvu0gL0Gw0he',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730715525495},
   {'date': '2024-10-18',
    'ssid': '7U93yo79GLG91qf6zNolYJ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729261952410},
   {'date': '2024-11-02',
    'ssid': '5XmvWwg8P6Igl0JICwfmld',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730567765999},
   {'date': '2024-10-29',
    'ssid': '7kC3euJn4QrhB4REDdoEHe',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730169247004},
   {'date': '2024-10-29',
    'ssid': '12nmxWJ85XL7cohJq1X0aG',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730175690746},
   {'date': '2024-11-07',
    'ssid': '4bZN4YphRR2iU5fTgmOwr9',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730957172277},
   {'date': '2024-10-18',
    'ssid': '5QyOn2vIrpVwvRYA8EGdzu',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729215619462},
   {'date': '2024-10-18',
    'ssid': '5g1Qz1Kys8nMz3r2mi0g62',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729283912722},
   {'date': '2024-10-09',
    'ssid': '4njDvgdObM4wz8z50NCMtl',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728486720915},
   {'date': '2024-10-29',
    'ssid': '3kgJ8ocCVQPUKB1HzbglmH',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730209052063},
   {'date': '2024-10-08',
    'ssid': 'Johjv0SzjWnLSovwM4Sjt',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728377876316},
   {'date': '2024-09-30',
    'ssid': '7Xo8UVCiDQIbISwu2Ae01H',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727719579204},
   {'date': '2024-10-14',
    'ssid': '2IRxUwlBnR7BlbFvMtSpG2',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728884033652},
   {'date': '2024-10-22',
    'ssid': '4jWOtoFn0baYfOqqCHT4Qk',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729560629404},
   {'date': '2024-10-16',
    'ssid': '49BW0SDXXlAUYlzepxwlQS',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729064388964},
   {'date': '2024-09-29',
    'ssid': 'mdrnJLjcezwOg9WjPAdwz',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727571168108},
   {'date': '2024-11-02',
    'ssid': '1XWsw8fWo6BjzgyviyaRJe',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730530424821},
   {'date': '2024-10-23',
    'ssid': 'NauvTjhbfzjeOlaKXTPHm',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729717432646},
   {'date': '2024-10-23',
    'ssid': '4yIhPm73Ea0J3fK71Xk2hK',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729695053680},
   {'date': '2024-11-01',
    'ssid': '1M3GsLLjcz5jETFGEo10Gs',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730468237179},
   {'date': '2024-10-21',
    'ssid': '4Roqz9ol40nQHV4tXIyDjh',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729496698511},
   {'date': '2024-10-29',
    'ssid': '6ZGoByncoHrI9rskPrheJB',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730201040929},
   {'date': '2024-10-26',
    'ssid': '1oWexEWdEd1z1xjpaLx16a',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1729923041690},
   {'date': '2024-10-19',
    'ssid': '4bjPUqLKe2RxRgfzCsIKND',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729347359599},
   {'date': '2024-10-28',
    'ssid': '3jdwYXYfzKK9f9rxTavwjF',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730076095959},
   {'date': '2024-10-29',
    'ssid': '2h3JKiaGnzxIGsTUIiih2c',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730163329682},
   {'date': '2024-10-21',
    'ssid': 'HUlfJBybiNVu2WAE0tYue',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729471935700},
   {'date': '2024-11-07',
    'ssid': 'G8ZPZbZDFoOP9VVl0wx0k',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730950134383},
   {'date': '2024-10-15',
    'ssid': '4B8XVqILEYNfoYbgAYM45j',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728982810990},
   {'date': '2024-10-07',
    'ssid': '39pnVUfZANLoS4ruYUxhLQ',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728262002175},
   {'date': '2024-10-25',
    'ssid': '4HJJ9xTm4pxBTDdaI2H9sO',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729815187622},
   {'date': '2024-10-13',
    'ssid': 'TJA59PC4AmjAAuxKVaGFs',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728809005027},
   {'date': '2024-11-01',
    'ssid': '7UwuzYrD25MsAIHJOAu4Sr',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730422620795},
   {'date': '2024-10-22',
    'ssid': '3AF0rcfK4hM6UMKmJiG3NP',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729611953587},
   {'date': '2024-10-27',
    'ssid': '4bjPUqLKe2RxRgfzCsIKND',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730046063169},
   {'date': '2024-10-08',
    'ssid': 'L3OOJN3ltFyMCCmpZ97e9',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728426192357},
   {'date': '2024-10-23',
    'ssid': '66az20ik9GNGX7LZkrynGQ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729715116224},
   {'date': '2024-10-19',
    'ssid': '3sAjI0JBf94rtrGh48PPox',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1729379345067},
   {'date': '2024-10-29',
    'ssid': '2kTkf7cyjNEseCB2ZbUr85',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730193636815},
   {'date': '2024-10-03',
    'ssid': '4yGkwlTGUOUtpE72uHgvAB',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727995654929},
   {'date': '2024-10-29',
    'ssid': '8x9eiHNYRSzMcum4XM1NQ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730194346316},
   {'date': '2024-11-05',
    'ssid': '3QUkt5bJimGptHNsibH4V5',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730824576915},
   {'date': '2024-10-19',
    'ssid': '3vbGI47Nmu79f5TAttJ5N0',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729325230308},
   {'date': '2024-10-19',
    'ssid': '3qALm5oqJOHMuMuODw0WGD',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729340972631},
   {'date': '2024-10-17',
    'ssid': '7VxR8R6xjGnEpO2n3wpucx',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729164042281},
   {'date': '2024-11-01',
    'ssid': '3xwzn8bVpDoMc0RJBxC0Q0',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730448193827},
   {'date': '2024-11-05',
    'ssid': '2xM3P2U6042HMt418M361s',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730781582274},
   {'date': '2024-10-06',
    'ssid': 'sYu7oXawMWQsM2ZfE4OOL',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728196445554},
   {'date': '2024-10-12',
    'ssid': '633ec1leYCsIWmlIFPzPTw',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728743627754},
   {'date': '2024-10-21',
    'ssid': '5DBcPrNCWRTX1kpcBAeEjs',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729515618905},
   {'date': '2024-11-03',
    'ssid': '3rUpSg8E3zXaZgsOUwLBP3',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730630912450},
   {'date': '2024-09-29',
    'ssid': '5hFs1Qa8raWpYoqmgfrlgh',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727606537318},
   {'date': '2024-10-12',
    'ssid': '1D8wp9OF3TLnmLv8n2AvSp',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728742092360},
   {'date': '2024-10-16',
    'ssid': '3EiRHSep8sBlq9Txn1Mm9d',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729084741603},
   {'date': '2024-10-01',
    'ssid': '5inzONsTvaIpuJYuzkWHl1',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727784760325},
   {'date': '2024-10-25',
    'ssid': '1Q6d9K39keE4tv2bpkfpNq',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729829088758},
   {'date': '2024-10-18',
    'ssid': '318F9uFhOGNPcqIHUQYcGt',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729217282441},
   {'date': '2024-10-21',
    'ssid': '156Gh9kH6G2zR8Jc7xazTq',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729501972744},
   {'date': '2024-11-03',
    'ssid': '4ofOmI3pW4QS8FlTT2uWDl',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730640632763},
   {'date': '2024-10-19',
    'ssid': '6DMrxZ0CZ9LmpOg6et87WD',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729309694988},
   {'date': '2024-10-15',
    'ssid': '10qSzyJTSIpwUbtgmnN1Ou',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728984090000},
   {'date': '2024-10-12',
    'ssid': '4iGLA7cb54brwpJIkfWNfe',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728737020712},
   {'date': '2024-10-25',
    'ssid': '4HJJ9xTm4pxBTDdaI2H9sO',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729815218756},
   {'date': '2024-10-19',
    'ssid': '5LHR7qbxjDjP2SqHIxUPCo',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1729310928129},
   {'date': '2024-10-14',
    'ssid': '3o27j2FnLzBgg63Bmea8LF',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728874594553},
   {'date': '2024-11-02',
    'ssid': '6OAiReqoZQmcvLZa44EQ8y',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730548183490},
   {'date': '2024-10-15',
    'ssid': '2MaukMo5AA0XhbVkJB2Elb',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728989908403},
   {'date': '2024-11-03',
    'ssid': '5Do3FamIpn8l4eoYppOJFI',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730609483923},
   {'date': '2024-11-07',
    'ssid': '6H9AqPHSEQdlMyMtsdUDRd',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730943756110},
   {'date': '2024-11-03',
    'ssid': '1ethGO4zBGJJF8v34c6FVU',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730626518760},
   {'date': '2024-11-07',
    'ssid': '2XKnYUHi6J69oZOOqly6d2',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730940937981},
   {'date': '2024-10-28',
    'ssid': '7QbJiJQE077Smds5m7LhOh',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730122008372},
   {'date': '2024-10-09',
    'ssid': '2xM3P2U6042HMt418M361s',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728434489098},
   {'date': '2024-10-30',
    'ssid': '704fHRrlntjFCbTHIf90jS',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730330817893},
   {'date': '2024-10-11',
    'ssid': '3V5b20qWppa8VqzocyiGBY',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728670457541},
   {'date': '2024-10-14',
    'ssid': 'AH4zycEl3YJmkSO3n0TbB',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728901085945},
   {'date': '2024-11-02',
    'ssid': '4b6box2xNccwBV739KQDYv',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730551601194},
   {'date': '2024-09-28',
    'ssid': '7JalDxZO36nWyzQAPVklGm',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727545411040},
   {'date': '2024-10-31',
    'ssid': '7ImV2WKxpg1oH2aegaq47d',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730410020428},
   {'date': '2024-10-13',
    'ssid': '2Tfn0VL41zCaZwhOPPp6zU',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728819479254},
   {'date': '2024-10-29',
    'ssid': '1cdY6B1zT7rQ7NH9I96JYL',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730231044920},
   {'date': '2024-10-14',
    'ssid': 'Uv7kZRX4zNcTHSi7VcCAV',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728898144490},
   {'date': '2024-11-05',
    'ssid': '59vGkduceP8xqlWSq4KREx',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730765942142},
   {'date': '2024-10-10',
    'ssid': '7DrY7sYh8omPOhaV820I6H',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728547461622},
   {'date': '2024-10-23',
    'ssid': '79J9H3CiQN1PWeBoMhlLcw',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729657590623},
   {'date': '2024-11-04',
    'ssid': '2R8MBqDQPqcFg9w53mZ9Hh',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730686993948},
   {'date': '2024-11-04',
    'ssid': '6WPCoEE2A6f4VGW9s4drnA',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730740440348},
   {'date': '2024-10-15',
    'ssid': '2kTkf7cyjNEseCB2ZbUr85',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729002448986},
   {'date': '2024-11-03',
    'ssid': '2PJiYMc8ECxAheG7tusfiW',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730619532992},
   {'date': '2024-11-04',
    'ssid': '3nleEzT2WBjdpPjnf7ovxx',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730685430712},
   {'date': '2024-10-29',
    'ssid': '1AA9YyyDcPwI0caVvvPWdB',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730199195247},
   {'date': '2024-10-01',
    'ssid': '2LoUWsNdsEwhkdKS8SVK8E',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727775413482},
   {'date': '2024-11-03',
    'ssid': '2SnyRIImyHVhyYL0GZxcTb',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730614907626},
   {'date': '2024-10-28',
    'ssid': '2BBDn29cq1egnLT4fEV4Is',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730122063673},
   {'date': '2024-11-04',
    'ssid': '7jFwKVE5JODKze4F0opOL7',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730720355310},
   {'date': '2024-10-23',
    'ssid': '4ezjke7utkHWChVhZH3nuS',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1729686030065},
   {'date': '2024-10-16',
    'ssid': '4YKhQX98GNAw4q5ARzvdL9',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729090524129},
   {'date': '2024-11-02',
    'ssid': '601YVL1EQsXO6XcgxIFelI',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730513530128},
   {'date': '2024-10-20',
    'ssid': '6XnGQPAZO8g2W7zjavPBYq',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729423662654},
   {'date': '2024-11-05',
    'ssid': '11OCVahTQsAcK3nSM3ZrOh',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730773271840},
   {'date': '2024-11-03',
    'ssid': '6QclmOxuzwz1OWfkXpv5Be',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730639989856},
   {'date': '2024-11-04',
    'ssid': '6OjOYZ9GNqnJXRAGKt9nC8',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730678919809},
   {'date': '2024-10-27',
    'ssid': '1477gF2yoCnC6EpZRnRH69',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730037911382},
   {'date': '2024-11-04',
    'ssid': '4AdCuXVGcfPEvNq4vBgH6Y',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730691088253},
   {'date': '2024-11-01',
    'ssid': '7XizlG6bEgj6ya38izt8FV',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730456406223},
   {'date': '2024-10-25',
    'ssid': '2PPCNsm4tZo75S8Zueo8SA',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729835531270},
   {'date': '2024-10-25',
    'ssid': '7RLl46b9y8qOL6wgnhzqNE',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729833867953},
   {'date': '2024-10-04',
    'ssid': '5BBQvoTmYlFXlkpo992W2n',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728011811661},
   {'date': '2024-11-02',
    'ssid': '3TrVfFvt328HhqZa8aqqYf',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730536631535},
   {'date': '2024-10-08',
    'ssid': '7WCx4Znet52xwOUAJAKtl8',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728377165547},
   {'date': '2024-11-07',
    'ssid': 'RqKgGkdtcDGRlp1X9MVmD',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1730980545892},
   {'date': '2024-10-03',
    'ssid': '4teHeM15Gl813NVg7mkeCV',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1727957234735},
   {'date': '2024-10-15',
    'ssid': '5zRChzBHUnV4HdRBbJOebT',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729001412620},
   {'date': '2024-11-04',
    'ssid': '39ZXPNooA0ajuN2R26MDap',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730755408976},
   {'date': '2024-10-16',
    'ssid': '7U93yo79GLG91qf6zNolYJ',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729087129582},
   {'date': '2024-10-22',
    'ssid': '1N8N1RIOewP0uKgAfuya4r',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729556110616},
   {'date': '2024-10-13',
    'ssid': '2ppQ7vIsqhFSsTSutZ1fN1',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1728808304977},
   {'date': '2024-10-10',
    'ssid': '1fqMbqALMR5JlFOVjzv0qM',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728562700029},
   {'date': '2024-11-01',
    'ssid': '1b8mfcomm8T0UEy7eOtrFm',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730466351614},
   {'date': '2024-11-07',
    'ssid': 'L7PXbAkCrvdmRiB22bJqR',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730948100438},
   {'date': '2024-10-28',
    'ssid': '2Uopn3acSZXExt00rGvMge',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730141642269},
   {'date': '2024-10-27',
    'ssid': '49c6wJjE6XdHybmHFLcc34',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730014410066},
   {'date': '2024-11-01',
    'ssid': '2fjXqsLZM2YO6PTGUXwNoH',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730435709473},
   {'date': '2024-10-26',
    'ssid': '3eCodw4QD53StnwIjquELG',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729962375941},
   {'date': '2024-10-29',
    'ssid': '3rHod53gXdj7JQ0d569AUl',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1730198710479},
   {'date': '2024-10-06',
    'ssid': '4EoE4IBoZTkKBCm4DyvLLL',
    'A:内购成功-总人数': 1,
    '#vp@event_date': 1728219217545},
   {'date': '2024-10-20',
    'ssid': '4vDQsU9hnXNxhbXfmzwlXA',
    'A:内购成功-总人数': 0,
    '#vp@event_date': 1729386382174},

In [63]:
login_df=pd.DataFrame(login.json()['data']['data'])[['ssid','#vp@event_date']]
ng_df=pd.DataFrame(ng.json()['data']['data'])[['ssid','#vp@event_date','A:内购成功-总人数']]

In [64]:
ng_df=ng_df[ng_df['A:内购成功-总人数']!=0]

In [65]:
ng_df['首次付费时间'] = pd.to_datetime(ng_df['#vp@event_date'],unit='ms')
login_df['活跃时间'] = pd.to_datetime(login_df['#vp@event_date'],unit='ms')

In [66]:
ng_df

,ssid,#vp@event_date,A:内购成功-总人数,首次付费时间
1,3kbNIGADBCxteZGwTujMkx,1728341201677,1,2024-10-07 22:46:41.677
15,5oa2UHSauccI29k7RSre1H,1728481247953,1,2024-10-09 13:40:47.953
17,FotJe5sNWwnJb5QFqDNav,1727946625272,1,2024-10-03 09:10:25.272
26,sSwaAtR47yVpGEjMG30R6,1728887846048,1,2024-10-14 06:37:26.048
31,CqpHSc6syDl9zhOgJmugZ,1728370206387,1,2024-10-08 06:50:06.387
...,...,...,...,...
13991,1o5iFLVCHExl1oUX0ykawL,1728404346637,1,2024-10-08 16:19:06.637
13992,2IjLCNzM1osP7f8ngCCNPJ,1730416279790,1,2024-10-31 23:11:19.790
14004,31JywTthgXJ4cXNMs2rjiq,1729078607769,1,2024-10-16 11:36:47.769
14007,78Q0ihOgHOWoVonwz3i7s,1730507657534,1,2024-11-02 00:34:17.534
14011,Zz45v4hOto2fiETMJOCs,1729235096449,1,2024-10-18 07:04:56.449

In [67]:
ng_df['付费日期'] =ng_df['首次付费时间'].dt.strftime('%Y-%m-%d')

In [68]:
login_df['活跃日期']=login_df['活跃时间'].dt.strftime('%Y-%m-%d')
login_df.drop_duplicates(subset=['活跃日期','ssid'],keep='first',inplace=True)

In [69]:
res = ng_df.merge(login_df[['ssid','活跃时间']],how='left',on='ssid')

In [70]:
res['生命周期']= (res['活跃时间'] -res['首次付费时间']).dt.days
res['付费日期'] =res['首次付费时间'].dt.strftime('%Y-%m-%d')

In [71]:
ng_df.groupby(by='付费日期',as_index=False)['ssid'].nunique()

          付费日期  ssid
0   2024-09-28    32
1   2024-09-29    46
2   2024-09-30    31
3   2024-10-01    35
4   2024-10-02    50
5   2024-10-03    40
6   2024-10-04    30
7   2024-10-05    67
8   2024-10-06    74
9   2024-10-07    55
10  2024-10-08    43
11  2024-10-09    57
12  2024-10-10    71
13  2024-10-11    55
14  2024-10-12    60
15  2024-10-13    53
16  2024-10-14    63
17  2024-10-15    52
18  2024-10-16    40
19  2024-10-17    48
20  2024-10-18    47
21  2024-10-19   106
22  2024-10-20    91
23  2024-10-21    83
24  2024-10-22    76
25  2024-10-23    75
26  2024-10-24    78
27  2024-10-25    68
28  2024-10-26    77
29  2024-10-27    64
30  2024-10-28    59
31  2024-10-29    40
32  2024-10-30    67
33  2024-10-31    80
34  2024-11-01    75
35  2024-11-02   123
36  2024-11-03   114
37  2024-11-04   116
38  2024-11-05   111
39  2024-11-06    68
40  2024-11-07    51

In [72]:
for i in range(0,42):
    print(i)
    res[f'{i}-D留存'] = res.apply(lambda x: x['ssid'] if x['生命周期']==i else np.nan,axis=1 )

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41

In [73]:
col_list=['ssid']+[f'{i}-D留存'  for i in range(42)]
df=res.groupby(by=['付费日期'],as_index=False)[col_list].agg({
    f'{j}':'nunique' for j in col_list
})

In [74]:
df.to_excel('../临时文件/0928-1107付费留存.xlsx')