In [48]:
import pandas as pd
import numpy as np

In [53]:
# 闯关数据 
data1=pd.read_csv('../临时文件/用户闯关数据.csv',index_col=False)[['Metric','用户唯一id','total_pay_num','事件发生时间']]

In [77]:
data1['ssid'].value_counts()

ssid
769CaRU8cQVECfzia7Ksin    274
6HDzjbSMf6umC3xjhWSxKB    240
19FISd0dPeWhdkXcNglnEl    147
YRpFSLiIJ1kXzdLY7PJ0Z     118
4a3YVzPDTfS1nifIUXM398    114
                         ...
457KGozM0QLuKBnxJIa6WE      1
323Ef6o4ApLplucMzT0Eif      1
6biZDyQYQI4NWjGjyuwVdH      1
49qsXswS7zE6eQClmcTAOg      1
5lMjUove1b1KZ639HkZKWR      1
Name: count, Length: 528, dtype: int64

In [55]:
data1['Metric']='闯关'

In [56]:
data1.columns=['event','ssid','累计付费次数','时间']

In [57]:
data1['时间']=pd.to_datetime(data1['时间'], unit='ms')

In [58]:
data1.head()

  event                    ssid  累计付费次数                      时间
0    闯关  6iOAk0MZic4MdznvGHQS2M    82.0 2024-08-14 04:45:12.398
1    闯关  38qRypwN8iCTHf1CtFNLCh     NaN 2024-08-21 08:58:19.551
2    闯关  4dpEC2wx5AsV4KO6zrYXkT     NaN 2024-08-24 14:23:09.980
3    闯关  1dHBjsb2K7d96T3uOCxpAh    34.0 2024-08-17 08:44:23.163
4    闯关  2OxOABYbOts0VXZn6KQ8lA    29.0 2024-08-18 12:50:47.007

In [59]:
# 付费数据
data2=pd.read_csv('../临时文件/用户付费数据.csv',index_col=False)[['Metric','用户唯一id','事件发生时间','Total']]

In [60]:
data2['Metric']='内购'

In [61]:
data2.columns=['event','ssid','时间','付费金额']

In [62]:
data2['时间']=pd.to_datetime(data2['时间'], unit='ms')

In [63]:
data2.head()

  event                    ssid                      时间  付费金额
0    内购   IysmpfoRA2nGv32zzhPFB 2024-09-02 13:29:21.308     1
1    内购  3VhSKapuZUijMlGPZDGK7B 2024-08-13 11:54:56.898     1
2    内购  60lWO4tL1riCPmY1dRpCvd 2024-09-06 11:20:29.625     1
3    内购  5RcUqBtRCyiVNhFL3tdIV4 2024-09-13 13:03:46.557     1
4    内购  55tqCook1pFLYVh1kCVJoJ 2024-09-09 01:52:33.423     1

In [64]:
# 合并数据
res=pd.concat((data1,data2))

In [80]:
res['ssid'].value_counts()

ssid
769CaRU8cQVECfzia7Ksin    274
6HDzjbSMf6umC3xjhWSxKB    240
19FISd0dPeWhdkXcNglnEl    147
6iOAk0MZic4MdznvGHQS2M    136
6GSkZrAhUjNmv4UNT25cu9    129
                         ...
28csFgCGMl1rDUKyQj7QRS      1
26kHPDGJd7FpSG5uxkPlm9      1
4kPfOZ6DKkcIakngK8rntJ      1
23HAy7cEczNTO4T45nk3rR      1
75E6NBqTzres0VQTt5AVDJ      1
Name: count, Length: 775, dtype: int64

In [81]:
res.to_excel('闯关付费数据汇总.xlsx')

In [65]:
# 根据时间排序
res.sort_values(by=['ssid','时间'],ascending=[True,True],inplace=True)

In [66]:
res.head()

     event                    ssid  累计付费次数                      时间  付费金额
649     内购  10hi1v1ne16RCC8Orxnmxm     NaN 2024-09-06 14:55:33.924   1.0
1106    内购  10hi1v1ne16RCC8Orxnmxm     NaN 2024-09-11 13:35:17.296   1.0
1547    闯关  10kFoJsdHtEcLLtBbKs6hn     NaN 2024-08-09 11:58:54.270   NaN
7190    闯关  10kFoJsdHtEcLLtBbKs6hn     NaN 2024-08-09 23:06:52.054   NaN
9478    闯关  10kFoJsdHtEcLLtBbKs6hn     NaN 2024-08-10 04:34:03.080   NaN

In [82]:
# 聚合事件
df=res.groupby(by=['ssid'],as_index=False)['event'].agg(lambda x:','.join(x))

In [83]:
df['ssid'].value_counts()

ssid
10hi1v1ne16RCC8Orxnmxm    1
5iwTODoSluVGtk8ctej89N    1
5v4zIvR1X5aXuJ5sR7rcem    1
5vRVC3CxAhWB9zb8AWQTks    1
5wrhcLZ5saSXror24JfEqR    1
                         ..
3VEu5ZNe18eNp6XTz9eNV9    1
3VggMFLo6FQyNMLMqGyFFm    1
3VhH6E0l7BoK33t6Vf0s9u    1
3VhSKapuZUijMlGPZDGK7B    1
zvc97aZA3YRwGzVagXBQH     1
Name: count, Length: 775, dtype: int64

In [84]:
df['event_list']=df['event'].str.split(',')

In [85]:
df.head()

,ssid,event,event_list
0,10hi1v1ne16RCC8Orxnmxm,"内购,内购","[内购, 内购]"
1,10kFoJsdHtEcLLtBbKs6hn,"闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯...","[闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯..."
2,11b1oUjtwgzVuOrstHELAb,"闯关,闯关,闯关,闯关,闯关,闯关,闯关","[闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关]"
3,13NpWBy0GmydvJ5PMeikbA,"闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯关,闯...","[闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯关, 闯..."
4,14Fe28wgweId5H6LDs2EkU,内购,[内购]

In [86]:
# 计算闯关失败次数 --> 付费路径
def get_level_ng_info(x):
    res_list=[]
    tmp_event = x[0]
    tmp_event_num=1
    if len(x)==1:
        res_list.append({tmp_event:tmp_event_num})
    else:
        for i in x[1:]:
            if i!=tmp_event:
                res_list.append({tmp_event:tmp_event_num})
                tmp_event=i
                tmp_event_num=1
                
            else:
                tmp_event_num +=1
        res_list.append({tmp_event:tmp_event_num})
    return res_list

In [87]:
df['失败-付费路径']=df.apply(lambda x:get_level_ng_info(x['event_list']),axis=1)

In [88]:
df.to_excel('../临时文件/用户闯关-付费路径.xlsx')