In [1]:
# 卡关定义：用户重复进行某一关闯关，且失败
# 后续行为：付费、流失、继续活跃
# 数据来源：JP-8.1-9.30

In [1]:
import pandas as pd
import numpy as np

In [7]:
df_count= pd.read_csv('../临时文件/10月付费金额和次数.csv',index_col=False).query('Metric=="B:内购次数"')[['当前最大章节id','googleShopID','Total']]
df_pay= pd.read_csv('../临时文件/10月付费金额和次数.csv',index_col=False).query('Metric=="A:内购金额"')[['当前最大章节id','googleShopID','Total']]

In [51]:
# 商品对照表
shopinfo = pd.read_excel('../临时文件/商品对照.xlsx')

In [16]:
shopinfo.columns=['name','price','googleShopID']

In [17]:
df_count=df_count.merge(shopinfo[['googleShopID','name']],how='left',on='googleShopID')
df_pay=df_pay.merge(shopinfo[['googleShopID','name']],how='left',on='googleShopID')

In [18]:
# 创建数据透视表
df_count.pivot_table(values="Total",# 计算字段
                      index="name",# 分组的行
                      columns="当前最大章节id",# 分组的列
                      aggfunc="sum", # 聚合方式
                      fill_value=0, # 对缺失值的填充，默认为nan
                      # margins=True, # 是否启用总计
                      # margins_name='总计' # 总计的名称
                     ).to_excel('../临时文件/关卡付费礼包次数.xlsx')

In [19]:
# 创建数据透视表
df_pay.pivot_table(values="Total",# 计算字段
                      index="name",# 分组的行
                      columns="当前最大章节id",# 分组的列
                      aggfunc="sum", # 聚合方式
                      fill_value=0, # 对缺失值的填充，默认为nan
                      # margins=True, # 是否启用总计
                      # margins_name='总计' # 总计的名称
                     ).to_excel('../临时文件/关卡付费礼包金额.xlsx')

In [2]:
# 10月付费用户闯关数据
df = pd.read_csv('../临时文件/10月用户闯关数据.csv',index_col=False)[['用户唯一id','事件发生时间','level_id','是否通关']]

In [115]:
# 计算每一关的闯关人数
df.query('level_id>=20&level_id<=40').groupby(by='level_id',as_index=False)['用户唯一id'].nunique()

    level_id  用户唯一id
0         20     816
1         21     696
2         22     706
3         23     676
4         24     630
5         25     471
6         26     422
7         27     432
8         28     398
9         29     382
10        30     374
11        31     287
12        32     235
13        33     203
14        34     195
15        35     191
16        36     148
17        37     151
18        38     173
19        39      80
20        40      91

In [117]:
# 计算关卡的人均失败次数
df1=df.query('level_id>=20&level_id<=40&是否通关==0').groupby(by='level_id',as_index=False)[['用户唯一id','事件发生时间']].agg({
    '用户唯一id':'nunique',
    '事件发生时间':'count'})

In [118]:
df1['人均失败次数']=df1['事件发生时间']/df1['用户唯一id']

In [120]:
# 计算首次和最后一次关卡的时间
df['时间']=pd.to_datetime(df['事件发生时间'],unit='ms')
result = df.groupby(by=['用户唯一id', 'level_id'], as_index=False).agg(
    时间_min=('时间', 'min'),
    时间_max=('时间', 'max')
)# 不会产生聚合索引

In [123]:
result['卡关天数']=(result['时间_max'] - result['时间_min']).dt.days

In [126]:
result.query('level_id>=20&level_id<=40').groupby(by='level_id',as_index=False)[['用户唯一id','卡关天数']].agg({
    '用户唯一id':'nunique',
    '卡关天数':'sum'
})

    level_id  用户唯一id  卡关天数
0         20     816  2160
1         21     696  1010
2         22     706  1620
3         23     676  2501
4         24     630  2710
5         25     471   783
6         26     422   561
7         27     432  1224
8         28     398  1176
9         29     382  1048
10        30     374  1584
11        31     287  1308
12        32     235   784
13        33     203   400
14        34     195   400
15        35     191   729
16        36     148   258
17        37     151   412
18        38     173  1128
19        39      80   272
20        40      91   506

In [4]:
df.head()

                   用户唯一id         事件发生时间  level_id  是否通关
0  5GXb3DOZe7r5oucUUTQ0Db  1728074768738        11     0
1  4D9vWUSapMfFS1uAjdFxBu  1728958800011        11     1
2  7Fk17cilKombqhm8FxDI93  1729347433331        20     0
3  1Ty6MZIC10BZB3GXJNVpG8  1728572909303        13     1
4  1J5DZpm45yNKPxcdaFER6a  1727927613761         7     0

In [129]:
# 20-41关的漏斗
level_ids=[i for i in range(20,42)]
for i in level_ids:
    df[f'闯关第{i}关'] = df.apply(lambda x:x['用户唯一id'] if x['level_id'] == i else np.nan,axis=1)
df1 = df.groupby(by='用户唯一id')[[f'闯关第{i}关' for i in range(20,42)]].agg({f'闯关第{i}关':'nunique' for i in range(20,42)})

In [131]:
# 活跃数据
df_login = pd.read_csv('../临时文件/10月用户登录数据.csv',index_col=False)

In [133]:
# 用户最后一次登录
df_login = df_login.groupby(by='用户唯一id',as_index=False)['事件发生时间'].max()

In [134]:
df_login['最后登录时间'] = pd.to_datetime(df_login['事件发生时间'],unit='ms')

In [135]:
# 连接用户
res1=df1.merge(df_login[['用户唯一id','最后登录时间']],how='left',on='用户唯一id')

In [138]:
# 判断关卡流失
# 1 用户还未进入20-40关
# 2 用户进入20-40关，计算用户最后所在关卡，和最后登录时间是否距离今日超过2天
def func2(x):
    # 默认最后一次闯关 = 19
    last_level=19
    for  i in  range(20,42):
        if x[f'闯关第{i}关']==1 :
            last_level = i
    if last_level ==19:
        return '尚未进入20-40关'
    else:
        loss_day = loss_day = (pd.to_datetime('2024-10-23') - x['最后登录时间']).days
        if loss_day >2:
            return last_level
        else:
            return '未流失'

res1['流失关卡'] = res1.apply(lambda x:func2(x),axis=1)

In [140]:
res1.groupby(by='流失关卡',as_index=False)['用户唯一id'].nunique()

          流失关卡  用户唯一id
0           20      20
1           21       7
2           22      34
3           23      26
4           24      35
5           25      19
6           26       9
7           27       8
8           28      12
9           29       7
10          30      21
11          31       8
12          32       2
13          33       2
14          34       5
15          35       7
16          36       2
17          37       2
18          38      19
19          39       2
20          40       9
21          41       4
22  尚未进入20-40关    4689
23         未流失     926

In [9]:
# 用户付费数据
df_ng=pd.read_csv('../临时文件/20-40关用户付费.csv',index_col=False)[['用户唯一id','事件发生时间','googleShopID','Total']]

In [11]:
df_ng['付费时间'] = pd.to_datetime(df_ng['事件发生时间'],unit='ms')

In [5]:
df['闯关时间'] = pd.to_datetime(df['事件发生时间'],unit='ms')

In [20]:
# 判断是否20-40关之间付费
# 计算用户闯关失败的时间
df_level_time=df.query('是否通关==0&level_id>=20&level_id<=40').pivot_table(values="闯关时间",# 计算字段
                      index="用户唯一id",# 分组的行
                      columns="level_id",# 分组的列
                      aggfunc="min", # 聚合方式
                      fill_value=0, # 对缺失值的填充，默认为nan
                      margins=False, # 是否启用总计
                      # margins_name='总计' # 总计的名称
                     )

In [21]:
df_level_time=df_level_time.merge(df_ng[['用户唯一id','付费时间','googleShopID','Total']],how='left',on='用户唯一id')

In [23]:
df_level_time.columns=['用户唯一id']+[f'{i}' for i in range(20,41)]+['付费时间', 'googleShopID','Total']

In [36]:
df_level_time.columns

Index(['用户唯一id', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40',
       '付费时间', 'googleShopID', 'Total'],
      dtype='object')

In [46]:
# 判断付费是否是在闯关失败后一天内进行
def func(x):
    if pd.isna(x['付费时间']):
        return '未付费用户'
    for i in range(20,41):
        if x[f'{i}']==0:
            continue
        if (x['付费时间']-x[f'{i}']).days <=1   and (x['付费时间']-x[f'{i}']).days >=0:
            print(x['付费时间'],x[f'{i}'])
            # print('卡关付费')
            return '卡关付费'
        else: 
            return '非卡关付费'

df_level_time['是否卡关付费'] = df_level_time.apply(lambda x:func(x),axis=1)

2024-10-22 14:18:22.434000 2024-10-22 14:08:47.568000
2024-10-06 05:51:01.361000 2024-10-06 05:32:13.856000
2024-10-14 02:44:03.469000 2024-10-13 03:16:35.652000
2024-10-14 02:16:43.025000 2024-10-13 03:16:35.652000
2024-10-19 07:17:20.609000 2024-10-19 06:38:30.309000
2024-10-19 06:50:02.287000 2024-10-19 06:38:30.309000
2024-10-12 19:42:01.094000 2024-10-12 06:41:12.079000
2024-10-22 10:27:59.934000 2024-10-22 10:27:42.132000
2024-10-08 16:18:34.441000 2024-10-08 16:01:49.262000
2024-10-22 04:53:40.160000 2024-10-20 09:53:24.332000
2024-10-13 04:25:34.639000 2024-10-12 16:00:39.971000
2024-10-14 12:15:14.180000 2024-10-12 16:00:39.971000
2024-10-13 04:41:13.220000 2024-10-12 16:00:39.971000
2024-10-14 04:54:04.507000 2024-10-12 16:00:39.971000
2024-10-13 09:21:42.531000 2024-10-12 16:00:39.971000
2024-10-14 04:43:26.853000 2024-10-12 16:00:39.971000
2024-10-19 01:51:33.585000 2024-10-19 00:25:30.600000
2024-10-19 01:44:40.776000 2024-10-19 00:25:30.600000
2024-10-19 01:46:04.201000 2024-10-19 00:25:30.600000
2024-10-19 01:42:14.628000 2024-10-19 00:25:30.600000
2024-10-11 12:37:32.916000 2024-10-10 10:51:10.295000
2024-10-11 12:19:25.186000 2024-10-09 14:19:17.061000
2024-10-11 12:19:06.434000 2024-10-09 14:19:17.061000
2024-10-02 03:13:56.174000 2024-10-01 03:39:40.765000
2024-10-02 12:43:58.064000 2024-10-02 12:06:29.921000
2024-10-02 12:36:08.838000 2024-10-02 12:06:29.921000
2024-10-03 13:39:57.218000 2024-10-02 12:06:29.921000
2024-10-13 23:36:40.094000 2024-10-13 01:07:02.356000
2024-10-14 02:52:22.435000 2024-10-13 01:07:02.356000
2024-10-14 09:52:42.524000 2024-10-14 09:33:36.938000
2024-10-14 12:59:57.173000 2024-10-14 09:33:36.938000
2024-10-21 13:23:11.247000 2024-10-21 10:06:18.537000
2024-10-21 13:22:53.656000 2024-10-21 10:06:18.537000
2024-10-17 03:30:41.587000 2024-10-16 02:24:46.648000
2024-10-17 04:33:53.784000 2024-10-16 02:24:46.648000
2024-10-17 04:35:14.809000 2024-10-16 02:24:46.648000
2024-10-16 03:11:53.461000 2024-10-16 02:24:46.648000
2024-10-17 23:07:26.518000 2024-10-16 03:37:58.178000
2024-10-14 11:08:26.171000 2024-10-14 11:07:11.221000
2024-10-22 04:00:23.708000 2024-10-21 16:17:56.900000
2024-10-22 04:00:08.244000 2024-10-21 16:17:56.900000
2024-10-11 13:12:34.658000 2024-10-11 10:22:03.015000
2024-10-13 05:12:44.979000 2024-10-11 10:22:03.015000
2024-10-13 05:11:53.998000 2024-10-11 10:22:03.015000
2024-10-12 17:06:47.960000 2024-10-11 10:22:03.015000
2024-10-12 17:08:22.320000 2024-10-11 10:22:03.015000
2024-10-12 17:08:09 2024-10-11 10:22:03.015000
2024-10-11 06:12:37.943000 2024-10-11 04:20:51.403000
2024-10-09 07:58:10.901000 2024-10-09 03:23:19.643000
2024-10-19 15:56:19.023000 2024-10-18 15:24:16.935000
2024-10-21 09:34:13.934000 2024-10-21 05:22:03.614000
2024-10-22 20:45:38.948000 2024-10-21 05:22:03.614000
2024-10-21 16:04:32.073000 2024-10-21 05:22:03.614000
2024-10-12 09:42:34.488000 2024-10-11 07:58:08.717000
2024-10-04 02:29:05.666000 2024-10-03 02:18:23.212000
2024-10-03 02:37:39.903000 2024-10-03 02:18:23.212000
2024-10-17 08:24:03.181000 2024-10-17 08:21:12.801000
2024-10-18 15:37:41.002000 2024-10-17 08:21:12.801000
2024-10-10 03:31:44.289000 2024-10-09 23:34:39.875000
2024-10-10 03:20:24.432000 2024-10-09 23:34:39.875000
2024-10-11 20:22:52.710000 2024-10-09 23:34:39.875000
2024-10-12 16:24:57.694000 2024-10-12 15:24:25.029000
2024-10-12 16:24:07.762000 2024-10-12 15:24:25.029000
2024-10-12 15:31:56.785000 2024-10-12 15:24:25.029000
2024-10-12 16:23:56.126000 2024-10-12 15:24:25.029000
2024-10-12 15:24:59.673000 2024-10-12 15:24:25.029000
2024-10-13 12:48:19.725000 2024-10-11 14:42:53.217000
2024-10-13 13:02:49.763000 2024-10-11 14:42:53.217000
2024-10-13 12:48:30.744000 2024-10-11 14:42:53.217000
2024-10-16 09:52:29.181000 2024-10-15 12:05:55.175000
2024-10-13 13:01:19.510000 2024-10-13 11:35:54.396000
2024-10-13 12:52:52.339000 2024-10-13 11:35:54.396000
2024-10-13 12:31:08.540000 2024-10-13 11:35:54.396000
2024-10-13 12:33:56.498000 2024-10-13 11:35:54.396000
2024-10-13 12:32:19.554000 2024-10-13 11:35:54.396000
2024-10-13 12:51:55.533000 2024-10-13 11:35:54.396000
2024-10-14 22:58:27.301000 2024-10-13 11:35:54.396000
2024-10-14 04:19:28.719000 2024-10-13 11:35:54.396000
2024-10-15 06:00:52.240000 2024-10-13 11:35:54.396000
2024-10-14 04:26:17.763000 2024-10-13 11:35:54.396000
2024-10-13 12:37:40.612000 2024-10-13 11:35:54.396000
2024-10-15 08:21:52.187000 2024-10-13 11:35:54.396000
2024-10-15 08:21:31.419000 2024-10-13 11:35:54.396000
2024-10-15 06:01:08.852000 2024-10-13 11:35:54.396000
2024-10-13 11:37:59.254000 2024-10-13 11:35:54.396000
2024-10-13 12:34:56.920000 2024-10-13 11:35:54.396000
2024-10-15 08:26:38.671000 2024-10-13 11:35:54.396000
2024-10-14 22:58:06.621000 2024-10-13 11:35:54.396000
2024-10-14 04:19:58.179000 2024-10-13 11:35:54.396000
2024-10-13 12:29:12.505000 2024-10-13 11:35:54.396000
2024-10-13 12:28:57.702000 2024-10-13 11:35:54.396000
2024-10-13 11:37:45.138000 2024-10-13 11:35:54.396000
2024-10-15 08:13:48.495000 2024-10-13 11:35:54.396000
2024-10-14 04:26:30.062000 2024-10-13 11:35:54.396000
2024-10-13 12:28:34.825000 2024-10-13 11:35:54.396000
2024-10-13 12:28:46.243000 2024-10-13 11:35:54.396000
2024-10-14 04:43:34.691000 2024-10-13 11:35:54.396000
2024-10-15 08:13:33.702000 2024-10-13 11:35:54.396000
2024-10-13 11:36:13.204000 2024-10-13 11:35:54.396000
2024-10-13 14:11:36.364000 2024-10-13 01:42:20.471000
2024-10-13 05:38:34.480000 2024-10-13 01:42:20.471000
2024-10-13 14:19:28.090000 2024-10-13 01:42:20.471000
2024-10-13 14:08:57.585000 2024-10-13 01:42:20.471000
2024-10-18 15:33:37.366000 2024-10-17 14:04:00.171000
2024-10-18 22:24:28.190000 2024-10-17 14:04:00.171000
2024-10-18 15:33:09.331000 2024-10-17 14:04:00.171000
2024-10-13 00:25:50.422000 2024-10-11 23:38:11.916000
2024-10-12 14:04:20.171000 2024-10-11 23:38:11.916000
2024-10-18 13:22:03.019000 2024-10-18 13:13:09.644000
2024-10-18 13:24:26.780000 2024-10-18 13:13:09.644000
2024-10-15 12:21:09.050000 2024-10-14 11:34:04.551000
2024-10-15 14:27:28.986000 2024-10-14 12:43:58.939000
2024-10-15 12:20:22.674000 2024-10-14 12:43:58.939000
2024-10-15 12:15:38.018000 2024-10-14 12:43:58.939000
2024-10-14 15:02:37.839000 2024-10-14 12:43:58.939000
2024-10-15 11:56:46.413000 2024-10-14 12:43:58.939000
2024-10-17 09:06:57.780000 2024-10-17 09:06:25.138000
2024-10-09 11:38:04.399000 2024-10-09 05:30:01.196000
2024-10-11 03:52:36.300000 2024-10-09 05:30:01.196000
2024-10-10 00:26:38.655000 2024-10-09 05:30:01.196000
2024-10-15 01:20:39.781000 2024-10-14 16:53:56.125000
2024-10-15 01:17:42.711000 2024-10-14 16:53:56.125000
2024-10-15 01:21:52.700000 2024-10-14 16:53:56.125000
2024-10-08 13:53:40.761000 2024-10-08 13:52:28.816000
2024-10-05 18:15:22.119000 2024-10-04 09:42:29.930000
2024-10-17 12:09:26.063000 2024-10-16 11:35:22.339000
2024-10-08 05:02:13.912000 2024-10-07 15:23:31.369000
2024-10-08 05:11:23.211000 2024-10-07 15:23:31.369000
2024-10-08 02:55:28.758000 2024-10-07 15:23:31.369000
2024-10-08 05:01:07.738000 2024-10-07 15:23:31.369000
2024-10-05 22:36:07.327000 2024-10-05 06:17:11.180000
2024-10-05 06:26:49.099000 2024-10-05 06:17:11.180000
2024-10-05 10:03:27.097000 2024-10-05 06:17:11.180000
2024-10-19 22:06:02.514000 2024-10-18 13:04:33.539000
2024-10-06 12:01:20.476000 2024-10-05 12:36:06.492000
2024-10-05 14:20:24.347000 2024-10-05 12:36:06.492000
2024-10-05 14:20:03.966000 2024-10-05 12:36:06.492000
2024-10-16 00:25:27.339000 2024-10-15 21:15:39.758000
2024-10-18 14:53:56.009000 2024-10-18 07:41:32.585000
2024-10-18 08:13:31.606000 2024-10-18 07:41:32.585000
2024-10-18 20:30:03.291000 2024-10-18 07:41:32.585000
2024-10-17 04:28:06.658000 2024-10-17 00:14:22.485000
2024-10-11 14:03:28.015000 2024-10-11 11:54:49.282000
2024-10-11 13:58:38.429000 2024-10-11 11:54:49.282000
2024-10-04 05:44:44.100000 2024-10-04 04:53:59.229000
2024-10-04 05:10:01.190000 2024-10-04 04:53:59.229000
2024-10-04 05:34:06.901000 2024-10-04 04:53:59.229000
2024-10-15 17:44:00.678000 2024-10-14 06:52:26.296000
2024-10-14 10:18:50.306000 2024-10-14 06:52:26.296000
2024-10-14 17:33:11.338000 2024-10-14 06:52:26.296000
2024-10-15 15:55:35.285000 2024-10-14 06:52:26.296000
2024-10-22 00:47:23.006000 2024-10-20 12:18:01.369000
2024-10-20 15:23:29.287000 2024-10-20 12:18:01.369000
2024-10-21 01:28:43.041000 2024-10-20 12:18:01.369000
2024-10-21 09:08:02.899000 2024-10-20 12:18:01.369000
2024-10-20 13:38:50.703000 2024-10-20 12:18:01.369000
2024-10-14 15:37:26.112000 2024-10-14 04:09:15.077000
2024-10-14 15:59:26.505000 2024-10-14 04:09:15.077000
2024-10-03 17:35:38.111000 2024-10-02 13:37:03.662000
2024-10-04 10:41:15.414000 2024-10-02 11:02:28.705000
2024-10-04 10:56:42.879000 2024-10-02 11:02:28.705000
2024-10-20 06:44:56.830000 2024-10-19 13:58:31.027000
2024-10-02 12:11:00.283000 2024-10-01 01:28:15.287000
2024-10-02 12:14:09.372000 2024-10-01 01:28:15.287000
2024-10-02 12:09:09.836000 2024-10-01 01:28:15.287000
2024-10-02 12:13:50.501000 2024-10-01 01:28:15.287000
2024-10-02 11:57:51.247000 2024-10-01 01:28:15.287000
2024-10-19 13:44:09.390000 2024-10-19 03:14:43.938000
2024-10-19 13:41:44.258000 2024-10-19 03:14:43.938000
2024-10-13 00:44:25.507000 2024-10-12 14:23:28.842000
2024-10-11 11:17:21.862000 2024-10-11 04:19:54.820000
2024-10-13 15:44:37.255000 2024-10-12 19:16:50.978000
2024-10-12 19:32:40.003000 2024-10-12 19:16:50.978000
2024-10-14 14:29:33.808000 2024-10-12 19:16:50.978000
2024-10-14 08:52:20.597000 2024-10-12 14:40:48.320000
2024-10-13 23:24:10.037000 2024-10-12 14:40:48.320000
2024-10-10 07:01:11.925000 2024-10-09 15:55:25.427000
2024-10-06 01:13:38.322000 2024-10-05 14:08:25.651000
2024-10-07 11:55:57.964000 2024-10-05 14:08:25.651000
2024-10-05 08:32:52.205000 2024-10-03 10:33:07.822000
2024-10-16 12:55:28.907000 2024-10-16 11:45:00.610000
2024-10-20 10:27:04.046000 2024-10-18 17:59:28.077000
2024-10-20 10:37:20.162000 2024-10-18 17:59:28.077000
2024-10-18 18:13:01.129000 2024-10-18 17:59:28.077000
2024-10-18 17:59:49.635000 2024-10-18 17:59:28.077000
2024-10-05 16:53:30.278000 2024-10-05 16:40:39.445000
2024-10-06 22:56:34.607000 2024-10-05 16:40:39.445000
2024-10-07 11:04:28.576000 2024-10-05 16:40:39.445000
2024-10-17 10:17:40.225000 2024-10-15 15:17:32.810000
2024-10-17 10:10:59.019000 2024-10-15 15:17:32.810000
2024-10-20 16:00:36.645000 2024-10-19 08:45:44.155000
2024-10-14 04:04:19.690000 2024-10-13 09:31:46.289000
2024-10-15 13:27:09.513000 2024-10-15 05:54:12.318000
2024-10-19 06:32:01.426000 2024-10-19 06:21:47.673000
2024-10-21 03:35:32.310000 2024-10-19 06:21:47.673000
2024-10-20 05:38:38.635000 2024-10-19 06:21:47.673000
2024-10-11 21:52:12.772000 2024-10-11 21:29:02.487000
2024-10-08 13:06:29.131000 2024-10-08 12:39:41.553000
2024-10-09 12:17:51.193000 2024-10-09 12:10:49.958000
2024-10-07 09:39:43.875000 2024-10-06 02:56:36.914000
2024-10-04 15:43:07.513000 2024-10-04 15:42:28.071000
2024-10-06 04:51:25.959000 2024-10-04 15:42:28.071000
2024-10-05 09:44:01.991000 2024-10-04 15:42:28.071000
2024-10-06 04:45:10.578000 2024-10-04 15:42:28.071000
2024-10-06 04:52:01.912000 2024-10-04 15:42:28.071000
2024-10-06 02:03:30.724000 2024-10-04 15:42:28.071000
2024-10-20 06:47:50.629000 2024-10-19 06:36:30.417000
2024-10-21 00:07:41.383000 2024-10-19 06:36:30.417000
2024-10-21 00:09:18.487000 2024-10-19 06:36:30.417000
2024-10-21 00:07:53.612000 2024-10-19 06:36:30.417000
2024-10-19 13:21:58.059000 2024-10-19 06:36:30.417000
2024-10-19 13:39:41.879000 2024-10-19 06:36:30.417000
2024-10-20 00:17:37.109000 2024-10-19 06:36:30.417000
2024-10-20 20:19:50.166000 2024-10-19 06:36:30.417000
2024-10-21 00:27:52.367000 2024-10-19 06:36:30.417000
2024-10-19 12:42:29.843000 2024-10-19 06:36:30.417000
2024-10-20 00:16:35.845000 2024-10-19 06:36:30.417000
2024-10-12 14:46:32.509000 2024-10-12 14:27:18.823000
2024-10-11 09:05:31.600000 2024-10-09 23:27:11.026000
2024-10-10 04:44:51.381000 2024-10-09 23:27:11.026000
2024-10-16 16:42:21.926000 2024-10-16 16:23:45.497000
2024-10-20 10:57:05.707000 2024-10-19 14:36:19.882000
2024-10-19 15:19:05.731000 2024-10-19 14:36:19.882000
2024-10-19 15:02:40.440000 2024-10-19 14:36:19.882000
2024-10-20 10:42:51.032000 2024-10-19 14:36:19.882000
2024-10-14 06:03:12.146000 2024-10-14 05:38:37.177000
2024-10-14 06:49:03.704000 2024-10-14 05:38:37.177000
2024-10-14 07:12:24.990000 2024-10-14 05:38:37.177000
2024-10-14 07:12:10.662000 2024-10-14 05:38:37.177000
2024-10-14 07:11:55.067000 2024-10-14 05:38:37.177000
2024-10-22 07:32:09.286000 2024-10-22 07:29:27.716000
2024-10-22 07:35:15.897000 2024-10-22 07:29:27.716000
2024-10-22 07:34:25.918000 2024-10-22 07:29:27.716000
2024-10-06 02:51:27.699000 2024-10-05 05:36:17.798000
2024-10-05 13:39:28.302000 2024-10-05 05:36:17.798000
2024-10-17 18:15:57.169000 2024-10-17 14:49:24.138000
2024-10-21 05:50:30.097000 2024-10-21 04:32:24.205000
2024-10-21 05:33:06.475000 2024-10-21 04:32:24.205000
2024-10-21 05:54:28.791000 2024-10-21 04:32:24.205000
2024-10-21 05:54:49.433000 2024-10-21 04:32:24.205000
2024-10-21 05:48:21.664000 2024-10-21 04:32:24.205000
2024-10-21 05:53:07.476000 2024-10-21 04:32:24.205000
2024-10-21 05:32:48.568000 2024-10-21 04:32:24.205000
2024-10-20 03:52:28.640000 2024-10-19 04:20:10.763000
2024-10-19 04:31:09.391000 2024-10-19 04:20:10.763000
2024-10-12 12:43:40.712000 2024-10-11 05:06:36.133000
2024-10-08 16:58:33.228000 2024-10-06 17:06:05.722000
2024-10-18 22:36:25.717000 2024-10-18 03:45:25.421000
2024-10-18 22:38:41.009000 2024-10-18 03:45:25.421000
2024-10-13 13:38:35.702000 2024-10-12 08:26:26.754000
2024-10-12 08:37:16.860000 2024-10-12 03:30:50.676000
2024-10-12 03:07:44.912000 2024-10-11 21:40:41.433000
2024-10-13 00:26:25.516000 2024-10-11 21:40:41.433000
2024-10-13 07:25:55.203000 2024-10-11 17:20:57.427000
2024-10-03 12:07:14.735000 2024-10-01 13:30:09.229000
2024-10-22 12:27:27.414000 2024-10-22 01:47:46.067000
2024-10-12 17:59:11.848000 2024-10-11 16:55:11.360000
2024-10-13 03:01:27.972000 2024-10-12 15:52:30.761000
2024-10-09 19:22:44.772000 2024-10-09 19:09:19.014000
2024-10-18 16:09:14.039000 2024-10-18 15:58:37.124000
2024-10-09 00:59:26.899000 2024-10-08 01:33:59.535000
2024-10-09 01:14:21.451000 2024-10-08 01:33:59.535000
2024-10-20 23:06:25.210000 2024-10-20 14:14:09.164000
2024-10-21 10:57:54.502000 2024-10-20 14:14:09.164000
2024-10-21 10:56:11.648000 2024-10-20 14:14:09.164000
2024-10-10 14:26:28.330000 2024-10-10 09:36:15.716000
2024-10-10 11:53:33.111000 2024-10-10 03:34:50.064000
2024-10-18 06:14:36.873000 2024-10-18 01:36:31.796000
2024-10-19 03:02:42.808000 2024-10-17 05:43:35.611000
2024-10-18 01:35:46.385000 2024-10-17 05:43:35.611000
2024-10-17 23:59:14.955000 2024-10-17 05:43:35.611000
2024-10-18 00:04:31.066000 2024-10-17 05:43:35.611000
2024-10-19 03:10:14.904000 2024-10-17 05:43:35.611000
2024-10-18 00:05:54.523000 2024-10-17 05:43:35.611000
2024-10-17 23:54:20.030000 2024-10-17 05:43:35.611000
2024-10-19 03:02:23.274000 2024-10-17 05:43:35.611000
2024-10-18 01:36:29.704000 2024-10-17 05:43:35.611000
2024-10-18 01:36:15.542000 2024-10-17 05:43:35.611000
2024-10-18 01:40:19.462000 2024-10-17 05:43:35.611000
2024-10-17 23:56:11.691000 2024-10-17 05:43:35.611000
2024-10-19 01:35:57.320000 2024-10-17 05:43:35.611000
2024-10-05 04:20:25.473000 2024-10-05 01:19:58.608000
2024-10-14 07:57:05.457000 2024-10-14 07:55:58.101000
2024-10-07 11:50:55.057000 2024-10-06 23:22:02.041000
2024-10-07 11:51:22.948000 2024-10-06 23:22:02.041000
2024-10-03 12:51:50.907000 2024-10-01 16:18:21.490000
2024-10-03 12:59:40.701000 2024-10-01 16:18:21.490000
2024-10-03 12:54:41.754000 2024-10-01 16:18:21.490000
2024-10-03 12:54:06.057000 2024-10-01 16:18:21.490000
2024-10-16 02:04:27.886000 2024-10-15 08:51:19.808000
2024-10-16 02:05:14.931000 2024-10-15 08:51:19.808000
2024-10-20 10:45:44.216000 2024-10-20 05:48:42.186000
2024-10-16 18:31:11.615000 2024-10-16 06:29:40.029000
2024-10-10 03:33:30.580000 2024-10-09 11:55:12.537000
2024-10-10 14:33:42.897000 2024-10-09 13:33:41.614000
2024-10-10 14:34:36.912000 2024-10-09 13:33:41.614000
2024-10-10 14:36:43.340000 2024-10-09 13:33:41.614000
2024-10-20 01:24:59.120000 2024-10-18 06:11:33.209000
2024-10-20 12:27:53.114000 2024-10-18 23:54:32.655000
2024-10-19 12:50:09.990000 2024-10-18 23:54:32.655000
2024-10-06 10:27:23.438000 2024-10-05 10:34:35.510000
2024-10-19 01:49:03.215000 2024-10-19 01:45:24.961000
2024-10-20 12:18:46.002000 2024-10-19 01:45:24.961000
2024-10-19 03:48:14.988000 2024-10-19 03:28:45.542000
2024-10-19 14:47:46.299000 2024-10-19 03:28:45.542000
2024-10-20 06:25:04.071000 2024-10-19 03:28:45.542000
2024-10-22 11:18:39.527000 2024-10-22 11:02:58.362000
2024-10-16 05:31:02.122000 2024-10-15 13:27:30.892000
2024-10-16 04:37:35.241000 2024-10-15 13:27:30.892000
2024-10-17 00:10:11.287000 2024-10-15 13:27:30.892000
2024-10-16 05:37:58.442000 2024-10-15 13:27:30.892000
2024-10-07 12:05:10.448000 2024-10-05 12:11:25.173000
2024-10-06 00:39:39.360000 2024-10-05 12:11:25.173000
2024-10-07 12:09:12.670000 2024-10-05 12:11:25.173000
2024-10-19 14:47:52.558000 2024-10-19 14:47:26.982000
2024-10-17 16:27:18.606000 2024-10-17 13:23:23.568000
2024-10-17 16:30:07.836000 2024-10-17 13:23:23.568000
2024-10-17 16:26:55.728000 2024-10-17 13:23:23.568000
2024-10-17 16:27:40.044000 2024-10-17 13:23:23.568000
2024-10-14 23:36:12.024000 2024-10-13 23:30:36.993000
2024-10-15 00:39:42.259000 2024-10-13 23:30:36.993000
2024-10-14 23:36:47.041000 2024-10-13 23:30:36.993000
2024-10-14 23:37:29.810000 2024-10-13 23:30:36.993000
2024-10-15 03:59:16.165000 2024-10-13 23:30:36.993000
2024-10-15 00:40:02.421000 2024-10-13 23:30:36.993000
2024-10-14 23:38:10.156000 2024-10-13 23:30:36.993000
2024-10-14 23:35:58.375000 2024-10-13 23:30:36.993000
2024-10-14 23:36:57.907000 2024-10-13 23:30:36.993000
2024-10-14 23:39:28.567000 2024-10-13 23:30:36.993000
2024-10-11 11:01:04.778000 2024-10-10 07:56:47.385000
2024-10-12 02:59:49.631000 2024-10-10 07:56:47.385000
2024-10-12 17:11:00.700000 2024-10-11 10:41:28.581000
2024-10-11 17:50:36.297000 2024-10-11 10:41:28.581000
2024-10-11 17:49:57.712000 2024-10-11 10:41:28.581000
2024-10-12 16:56:38.645000 2024-10-11 10:41:28.581000
2024-10-16 02:32:08.236000 2024-10-15 02:01:28.999000
2024-10-16 01:29:42.559000 2024-10-15 02:01:28.999000
2024-10-20 11:27:42.654000 2024-10-19 12:51:49.392000
2024-10-15 01:49:33.522000 2024-10-14 14:42:06.086000
2024-10-15 01:57:25.117000 2024-10-14 14:42:06.086000
2024-10-15 02:04:11.345000 2024-10-14 14:42:06.086000
2024-10-13 16:45:38.220000 2024-10-13 16:23:20.837000
2024-10-18 02:37:45.059000 2024-10-16 11:51:00.868000
2024-10-17 08:10:48.867000 2024-10-16 11:51:00.868000
2024-10-18 05:02:44.704000 2024-10-16 11:51:00.868000
2024-10-17 03:00:46.679000 2024-10-16 11:51:00.868000
2024-10-17 02:43:41.119000 2024-10-16 11:51:00.868000
2024-10-10 09:30:10.011000 2024-10-08 14:47:51.628000
2024-10-09 13:50:25.910000 2024-10-08 14:47:51.628000
2024-10-02 07:10:39.451000 2024-10-01 03:49:53.784000
2024-10-02 03:58:30.545000 2024-10-01 03:49:53.784000
2024-10-12 01:12:36.681000 2024-10-10 12:49:09.236000
2024-10-14 02:12:44.522000 2024-10-13 08:06:54.668000
2024-10-14 01:26:20.402000 2024-10-13 08:06:54.668000
2024-10-12 21:37:22.618000 2024-10-12 12:43:32.928000
2024-10-13 14:48:31.663000 2024-10-12 12:43:32.928000
2024-10-21 12:08:21.933000 2024-10-21 01:48:14.620000
2024-10-21 12:34:57.553000 2024-10-21 01:48:14.620000
2024-10-21 11:50:26.932000 2024-10-21 01:48:14.620000
2024-10-21 12:05:57.832000 2024-10-21 01:48:14.620000
2024-10-03 12:18:25.377000 2024-10-03 12:17:36.635000
2024-10-08 16:52:24.579000 2024-10-08 15:39:35.541000
2024-10-09 01:22:00.116000 2024-10-08 15:39:35.541000
2024-10-13 05:23:01.747000 2024-10-11 14:50:20.233000
2024-10-15 15:02:27.460000 2024-10-14 14:31:24.702000
2024-10-17 22:16:04.429000 2024-10-16 16:48:36.330000
2024-10-17 01:40:26.317000 2024-10-16 16:48:36.330000
2024-10-16 17:02:15.146000 2024-10-16 16:48:36.330000
2024-10-05 07:44:42.937000 2024-10-04 11:22:12.522000
2024-10-12 10:51:20.713000 2024-10-11 06:41:41.342000

In [47]:
df_level_time.groupby(by='是否卡关付费',as_index=False)[['用户唯一id','Total']].agg({
    '用户唯一id':'nunique',
    'Total':'sum'
})

  是否卡关付费  用户唯一id    Total
0   卡关付费     192   4698.0
1  未付费用户     625      0.0
2  非卡关付费     508  28872.0

In [50]:
df_ng_info=df_level_time.query('是否卡关付费=="卡关付费"').groupby(by='googleShopID',as_index=False)[['付费时间','Total']].agg({
    '付费时间':'count','Total':'sum'})

In [53]:
shopinfo.columns=['name','price','googleShopID']

In [55]:
df_ng_info=df_ng_info.merge(shopinfo,how='left',on='googleShopID')

In [56]:
df_ng_info.to_excel('../临时文件/卡关主要购买礼包.xlsx',index=False)

In [104]:
df4=df3.merge(df[['用户唯一id','level_id']],how='left',on='用户唯一id')

In [106]:
df4.groupby(by='level_id_y')['用户唯一id'].nunique().to_csv('../临时文件/每一关活跃.csv')

In [79]:
df['闯关时间']=pd.to_datetime(df['事件发生时间'],unit='ms')

In [80]:
# 10月付费用户登录数据
df2 = pd.read_csv('../临时文件/10月付费用户登录.csv',index_col=False)[['用户唯一id','事件发生时间']]
df2['登录时间']=pd.to_datetime(df2['事件发生时间'],unit='ms')

In [81]:
# 计算用户每一关的最后一次闯关时间
df['关卡最后闯关时间'] = df.groupby(by=['用户唯一id','level_id'])['闯关时间'].transform('max')

In [82]:
# 前41关的漏斗
level_ids=[i for i in range(2,42)]
for i in level_ids:
    df[f'闯关第{i}关'] = df.apply(lambda x:x['用户唯一id'] if x['level_id'] == i else np.nan,axis=1)

In [83]:
df=df.groupby(by='用户唯一id')[[f'闯关第{i}关' for i in range(2,42)]].agg({f'闯关第{i}关':'nunique' for i in range(2,42)})

In [86]:
# 用户最后一次登录时间
df2=df2.groupby(by='用户唯一id',as_index=False)['登录时间'].max()

In [87]:
# 连接登录时间，判断用户具体流失关卡
# 1. 用户顺利进入到下一关
# 2. 用户没有进入下一关，且最后一次登录距离今日超过2日
res= df.merge(df2,how='left',on='用户唯一id')

In [88]:
# 流失判断：
def loss_func(x):
    # 最后关卡位置,默认第二关
    loss_level=2
    for  i in  range(2,42):
        if x[f'闯关第{i}关']==1 :
            loss_level = i 
    #判断最后一次登录时间距离今日的差距天数
    loss_day = (pd.to_datetime('2024-10-23') - x['登录时间']).days
    if loss_day <= 2:
        loss_level ='尚未流失'
    return loss_level

res['流失关卡'] = res.apply(lambda x:loss_func(x),axis=1)
res=res.query('闯关第2关==1')

In [93]:
res['用户唯一id'].nunique()

1229

In [95]:
res.query('流失关卡==3')[['用户唯一id']].to_excel('../临时文件/第三关流失付费用户.xlsx',index=False)

In [91]:
res.groupby(by='流失关卡',as_index=False)['用户唯一id'].nunique()

    流失关卡  用户唯一id
0      2      25
1      3     123
2      4      27
3      5      24
4      6      25
5      7      19
6      8       5
7      9      12
8     10      21
9     11       6
10    12       4
11    13       4
12    14       4
13    15       5
14    16       2
15    17       5
16    18       3
17    19       2
18    20       4
19    21       1
20    22       7
21    23       2
22    24       9
23    25       4
24    26       2
25    27       1
26    30       1
27    33       1
28    34       1
29  尚未流失     880

In [8]:
df_pay.head()

   当前最大章节id              googleShopID  Total
1       3.0       tales_no_ad_forever   1611
2       3.0             tales_award_2   1262
5       3.0             tales_award_3    560
7       3.0             tales_award_1    530
9       4.0  tales_super_monthly_card    480

In [111]:
# 闯关数据
df1 = pd.read_csv('../临时文件/9月用户卡关.csv',index_col=False)[['用户唯一id','事件发生时间','level_id']]

In [112]:
df1['时间']=pd.to_datetime(df1['事件发生时间'],unit='ms')

In [113]:
df1.head()

                   用户唯一id         事件发生时间  level_id                      时间
0  7dxolq9SaVx0DU7blY5VNu  1725381179503         7 2024-09-03 16:32:59.503
1  2RS8G4PzakcunMyzisreLS  1725593953395        27 2024-09-06 03:39:13.395
2  3AuAGaZS7rCFTDtnELHTaK  1725631177822        10 2024-09-06 13:59:37.822
3  1ZxEiZIVe5ftymmBTfkALD  1725177352087         1 2024-09-01 07:55:52.087
4  5RukvsaAQD3RRuIN15TZYn  1726012098177        38 2024-09-10 23:48:18.177

In [9]:
# 活跃数据
df2 = pd.read_csv('../临时文件/9月用户活跃.csv',index_col=False)[['用户唯一id','事件发生时间']]

In [10]:
df2['活跃时间']=pd.to_datetime(df2['事件发生时间'],unit='ms')

In [11]:
df2.head()

                   用户唯一id         事件发生时间                    活跃时间
0  3mkkQ9DhxUffDYGfiOIxrE  1727838743375 2024-10-02 03:12:23.375
1  13namfQBRu8wjF3yYoN6Xs  1727971245577 2024-10-03 16:00:45.577
2  4H05TEyXGn20wqmKsk5wm5  1727404974845 2024-09-27 02:42:54.845
3  4k8q0HaTe09NhDVteg1lqs  1727951639526 2024-10-03 10:33:59.526
4  1xLV8uRzEjPXty52SoqD0c  1727513663312 2024-09-28 08:54:23.312

In [12]:
# 付费数据
df3=pd.read_csv('../临时文件/9月用户付费.csv',index_col=False)[['用户唯一id','事件发生时间']]

In [13]:
df3['付费时间']=pd.to_datetime(df3['事件发生时间'],unit='ms')

In [14]:
df3.head()

                   用户唯一id         事件发生时间                    付费时间
0   IysmpfoRA2nGv32zzhPFB  1725283761308 2024-09-02 13:29:21.308
1  1cvDmwbp0MLZfezs9ficVt  1727783339449 2024-10-01 11:48:59.449
2  60lWO4tL1riCPmY1dRpCvd  1725621629625 2024-09-06 11:20:29.625
3   NNy3gzVWsriONSkPJaXie  1727830209890 2024-10-02 00:50:09.890
4  5XwOft7FU5gDwM0WHM2hNv  1727976857077 2024-10-03 17:34:17.077

In [114]:
# 计算用户最后一次卡关
df1['卡关顺序']=df1.groupby(by='用户唯一id')['level_id'].rank(ascending=False,method='dense')

In [167]:
# 计算每一关失败次数
res_stuck=df1.query('level_id>=20').groupby(by=['用户唯一id','level_id'],as_index=False)[['事件发生时间','时间']].agg({
    '事件发生时间':'count',
    '时间':'min'
})

In [173]:
res_stuck.columns=['用户唯一id','关卡id','失败次数','失败时间']

In [174]:
for i in range(20,31):
    col_name = f'卡{i}关时间'
    res_stuck[col_name] = res_stuck.apply(lambda x: x['失败时间'] if x['关卡id'] == i else np.nan,axis=1)

In [177]:
res_stuck=res_stuck.query('失败次数>3').groupby(by='用户唯一id',as_index=False)[[f'卡{i}关时间' for i in range(20,31)]].agg({
    f'卡{i}关时间':'max' for i in range(20,31)
})

In [178]:
# 卡关过程中是否付费
res_stuck_ng=res_stuck.merge(df_ng,how='left',on='用户唯一id')

In [181]:
def func1(x):
    time_list =[x[f'卡{i}关时间'] for i in range(20,31)]
    
    if x['付费时间'] >min(time_list) and x['付费时间']< max(time_list):
        return '是'
    else:
        return '否'

In [184]:
res_stuck_ng['是否卡关付费'] = res_stuck_ng.apply(lambda x:func1(x),axis=1)

In [187]:
res_stuck_ng['用户唯一id'].nunique()

631

In [186]:
# 计算卡每一关时间的
res_stuck_ng.groupby(by = '是否卡关付费')[['用户唯一id']].nunique()

        用户唯一id
是否卡关付费
否          626
是           16

In [188]:
level_df.head()

                   用户唯一id  卡关关卡  失败次数                    失败时间
0  102PihDDyyWvmxweVcCtLt     3     1 2024-09-04 02:02:26.375
1  103JTlgz3Bh2LZhuXlNI0y    10     4 2024-09-28 23:29:24.925
2  10cFSByYSnO8b3fPo2gPhP     5     1 2024-09-10 06:18:16.153
3  10hi1v1ne16RCC8Orxnmxm    31    24 2024-09-23 21:27:10.020
4  10kFoJsdHtEcLLtBbKs6hn    35    20 2024-09-01 01:05:28.780

In [198]:
df1_new=df1[df1['卡关顺序']==1].groupby(by=['用户唯一id','level_id'],as_index=False).agg(
    时间_min=('时间', 'min'),
    时间_max=('时间', 'max')
)

In [201]:
df1_new['卡关天数'] = (df1_new['时间_max'] - df1_new['时间_min']).dt.days

In [204]:
df1_new.query('level_id>=20').groupby(by='level_id',as_index=False)['卡关天数'].sum()

    level_id  卡关天数
0         20    94
1         21    27
2         22   195
3         23   334
4         24   578
5         25   119
6         26    15
7         27   176
8         28   177
9         29    70
10        30   382
11        31   113
12        32   182
13        33    20
14        34    42
15        35    35
16        36     5
17        37     1
18        38   437
19        39    76
20        40   400
21        41     0
22        42    14
23        44    47
24        45     9
25        46    17
26        47     8
27        48     0
28        49     0
29        50     0
30        51    20
31        53    58
32        55     1
33        56     0
34        60     8
35        65    15
36        69     1
37        70    44
38        71     1
39        74    22
40        80     7
41        91    15
42        95     3
43       100     0
44       103     2
45       109     0
46       110     0

In [116]:
level_df = df1[df1['卡关顺序']==1].groupby(by=['用户唯一id','level_id'],as_index=False)[['卡关顺序','时间']].agg({
    '卡关顺序':'count',
    '时间':'min'}
)

In [117]:
level_df.columns=['用户唯一id','卡关关卡','失败次数','失败时间']

In [122]:
df_ng = pd.read_csv('../临时文件/卡关用户付费.csv',index_col=False)[['用户唯一id','事件发生时间','Total']]

In [124]:
df_ng['付费时间']=pd.to_datetime(df_ng['事件发生时间'],unit='ms')

In [126]:
res_ng=level_df.query('卡关关卡>=20').merge(df_ng[['用户唯一id','付费时间','Total']],how='left',on='用户唯一id')

In [129]:
# 卡关前后付费对比
res_ng=res_ng[res_ng['Total'].notnull()]

In [131]:
res_ng['卡关前后'] = res_ng.apply(lambda x:'卡关后' if x['付费时间']>x['失败时间'] else'卡关前',axis=1)

C:\Users\admin\AppData\Local\Temp\ipykernel_17384\2880005215.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_ng['卡关前后'] = res_ng.apply(lambda x:'卡关后' if x['付费时间']>x['失败时间'] else'卡关前',axis=1)

In [135]:
res_ng['用户唯一id'].nunique()

267

In [134]:
res_ng.groupby(by='卡关前后')[['用户唯一id','Total']].agg({
    '用户唯一id':'nunique',
    'Total':'sum'
})

      用户唯一id    Total
卡关前后
卡关前      261  17419.0
卡关后       73   1766.0

In [136]:
level_df.query('卡关关卡>=20')['用户唯一id'].nunique()

758

In [137]:
# 卡关后流失，统一生命周期
df_user = level_df.query('卡关关卡>=20')

In [138]:
res_loss = df_user.merge(df2,how='left',on='用户唯一id')

In [140]:
res_loss['生命周期']=(res_loss['活跃时间'] - res_loss['失败时间']).dt.days

In [143]:
res_loss.query('生命周期>0').groupby(by='生命周期',as_index=False)['用户唯一id'].nunique()

    生命周期  用户唯一id
0      1     574
1      2     535
2      3     504
3      4     412
4      5     360
5      6     313
6      7     274
7      8     264
8      9     218
9     10     195
10    11     188
11    12     167
12    13     145
13    14     139
14    15     136
15    16     109
16    17      96
17    18      91
18    19      90
19    20      78
20    21      71
21    22      70
22    23      74
23    24      59
24    25      50
25    26      46
26    27      45
27    28      34
28    29      36
29    30      28
30    31      22
31    32      19

In [145]:
res_pay = df_user.merge(df_ng,how='left',on='用户唯一id')
res_pay = res_pay[res_pay['付费时间'].notnull()]
res_pay['生命周期']=(res_pay['付费时间'] - res_pay['失败时间']).dt.days

In [146]:
res_pay.query('生命周期>=0').groupby(by='生命周期',as_index=False)[['用户唯一id','Total']].agg({
    '用户唯一id':'nunique',
    'Total':'sum'
})

    生命周期  用户唯一id  Total
0      0      26  343.0
1      1      17  349.0
2      2      16  130.0
3      3      17  185.0
4      4      11   90.0
5      5       7   56.0
6      6       7  123.0
7      7       7   38.0
8      8       5   49.0
9      9       5  165.0
10    10       4   29.0
11    11       5   43.0
12    12       4    9.0
13    13       1    4.0
14    14       3   13.0
15    15       2    7.0
16    16       1    8.0
17    17       1   11.0
18    18       2   19.0
19    19       3    6.0
20    20       3   34.0
21    21       2   22.0
22    23       1    8.0
23    24       2    5.0
24    26       1    6.0
25    29       1   14.0

In [119]:
level_df.query('卡关关卡>=20').groupby(by='卡关关卡')[['用户唯一id','失败次数']].agg({
    '用户唯一id':'nunique',
    '失败次数':'sum'
})

      用户唯一id  失败次数
卡关关卡
20        40   184
21        20    60
22        50   361
23        76   744
24       113   793
25        35   418
26         9    38
27        32   331
28        47   688
29        22   224
30        72   938
31        28   301
32        36   266
33         5    30
34        12    71
35        14    72
36         5    41
37         4    17
38        40  1882
39        10   319
40        28   888
41         2     3
42         2    33
44         5   117
45         3    14
46         3    46
47         3    37
48         1     5
49         1    10
50         3     9
51         2    10
53         9   158
55         1     9
56         1     8
60         5    64
65         2   131
69         2    20
70         3   484
71         1     6
74         1    10
80         1     5
91         1     9
95         2    27
100        1     8
103        3    16
109        1    10
110        1     1

In [75]:
# 卡关后付费
level_df= level_df.merge(df3,how='left',on='用户唯一id')

In [76]:
level_df['卡关后付费']=level_df.apply(lambda x:'是' if x['付费时间']>x['失败时间'] else '否',axis=1)

In [78]:
level_df.groupby(by='卡关后付费',as_index=False)['用户唯一id'].nunique()

  卡关后付费  用户唯一id
0     否    2761
1     是     176

In [79]:
level_df['用户唯一id'].nunique()

2837

In [80]:
# 卡关后流失
level_df2 = df1[df1['卡关顺序']==1].groupby(by=['用户唯一id','level_id'],as_index=False)[['卡关顺序','时间']].agg({
    '卡关顺序':'count',
    '时间':'max'}
)

In [81]:
level_df2.columns=['用户唯一id','卡关关卡','失败次数','失败时间']

In [82]:
# 卡关后流失
level_df2= level_df2.merge(df2,how='left',on='用户唯一id')

In [92]:
level_df2['活跃时间差'] = (level_df2['活跃时间'] - level_df2['失败时间']).dt.days

In [108]:
level_df2['是否流失'] = level_df2.apply(lambda x: '否' if x['活跃时间差']>=1 else '是',axis=1)

In [109]:
level_df2.groupby(by='是否流失',as_index=False)['用户唯一id'].nunique()

  是否流失  用户唯一id
0    否    1324
1    是    2836

In [110]:
level_df2['用户唯一id'].nunique()

2837

In [149]:
df4 = pd.read_csv('../临时文件/卡关用户挑战.csv',index_col=False)[['change_name','用户唯一id','事件发生时间']]

In [150]:
df4['挑战时间']=pd.to_datetime(df4['事件发生时间'],unit='ms')

In [151]:
res_chall=level_df.query('卡关关卡>=20').merge(df4,how='left',on='用户唯一id')

In [153]:
res_chall.query('挑战时间>失败时间').groupby(by='change_name',as_index=False)['用户唯一id'].nunique()

  change_name  用户唯一id
0        gold     180
1       tower     504

In [158]:
df5 =pd.read_csv('../临时文件/卡关用户废墟探索.csv',index_col=False)[['用户唯一id','事件发生时间']]

In [159]:
df5['探索时间'] = pd.to_datetime(df5['事件发生时间'],unit='ms')

In [161]:
res_exp=level_df.query('卡关关卡>=23').merge(df5[['用户唯一id','探索时间']],how='left',on='用户唯一id')

In [163]:
res_exp.query('探索时间>失败时间')['用户唯一id'].nunique()

322

In [164]:
res_exp['用户唯一id'].nunique()

648